### ISSUE TITLE
Move to wakuconnect.dev

### ISSUE THREAD

**Issue by D4nte** [vacp2p/dappconnect.dev#13]
We are renaming DappConnect to WakuConnect

@jakubgs Could you please move this website from dappconnect.dev to wakuconnect.dev (the domain name has already been acquired).

**Comment by jakubgs** [comment]
We will need to transfer the domain ownership to our main Gandi account and set it up with CloudFlare.

**Comment by jakubgs** [comment]
Done: https://dev.wakuconnect.dev/
Changes:
* https://github.com/vacp2p/wakuconnect.dev/commit/6c60d75b - ci: update domain to wakuconnect.dev
* https://github.com/status-im/infra-misc/commit/f9126d80 - sites: move dappconnect.dev to wakuconnect.dev
