### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by D4nte** [vacp2p/dappconnect.dev#3]
@D4nte to provide missing links.

- [x] Docs
  - [x] Quick Start: https://docs.dappconnect.dev/quick_start.html
  - [x] Guides: https://docs.dappconnect.dev/guides/index.html
  - [x] Docs: https://docs.dappconnect.dev
  - [x] GitHub: https://github.com/status-im/?q=dappconnect&type=&language=&sort=
- [x] Use Cases: https://github.com/vacp2p/docs.dappconnect.dev/issues/12
- [x] About us: ???
- [x] Get Started: https://docs.dappconnect.dev/quick_start.html
- [x] See the docs: https://docs.dappconnect.dev
- [x] Get inspired, view more use cases: https://github.com/vacp2p/docs.dappconnect.dev/issues/12
  - [x] Decentralized Chat, view the guide: TBD
  - [x] Gasless Polling, view the guide: TBD
  - [x] dApp to Wallet Notifications, view the guide: TBD
  - [x] Layer 2 Communication, view the guide: TBD
- [x] Learn more about Waku: Waku website
- [x] Use DappConnect for decentralized communications now, Get started: TBD
- [x] Twitter: https://twitter.com/dappconnect
- [x] Discord: discord.gg/NgQERkYbHD
- [x] GitHub: https://github.com/status-im/?q=dappconnect&type=&language=&sort=
- [x] Forum: https://forum.vac.dev/ 
- [x] Blog: https://vac.dev/research-log/ (link to the new Vac blog)
- [x] Footer links
  - [x] About ???

**Comment by D4nte** [comment]
@oskarth I don't see an "About us" or "Team" section in the vac.dev website. Is that on purpose?
I wonder if I should just remove the "About us" link in the present website then.
Or I could replace "About us" with About Waku" & "About Vac".

**Comment by oskarth** [comment]
We deliberately removed it I think, but an about page is not a bad idea. I think once Jinho et al get current sites up we can iterate based on that

**Comment by D4nte** [comment]
Ok, I'll remove the link for now
